# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0063_auto_20171219_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Workflow Version'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Workflow Version'),
        ),
    ]
