# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-05 02:32
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def set_version(apps, schema_editor):
    Course = apps.get_model('publisher', 'Course')

    for course in Course.objects.filter(Q(version__isnull=True)):
        course.version = 0
        course.save()


class Migration(migrations.Migration):
    dependencies = [
        ('publisher', '0064_auto_20180123_1859'),
    ]

    operations = [
        migrations.RunPython(set_version, reverse_code=migrations.RunPython.noop)
    ]
