# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0076_auto_20171219_1841'),
        ('core', '0007_auto_20171004_1133'),
        ('publisher', '0065_set_course_verison'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEntitlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='publisher.Course')),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, related_name='publisher_entitlements', to='core.Currency')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_entitlements', to='course_metadata.SeatType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courseentitlement',
            unique_together=set([('course', 'mode')]),
        ),
    ]
